### ISSUE TITLE
Setup interface to BLS

### ISSUE THREAD

**Issue by mdnip** [xi-project-team/xi-project-backend#3]
API: http://www.bls.gov/developers/

**Comment by buschm2rpi** [comment]
Countly-level geographic information on aggregate wages and employment by industry: 
http://www.bls.gov/cew/datatoc.htm

County-level labor statistics, employment rates, unemployment rates: 
http://www.bls.gov/lau/#tables

**Comment by hiles8500** [comment]
Here is a better link than datatoc.  Http://www.bls.gov/opendata.htm

**Comment by hiles8500** [comment]
Oops, should be:
http://www.bls.gov/cew/opendata.htm

**Comment by mdnip** [comment]
BLS data is now in the S3 data bucket.
